FROM maven:3.9.0-amazoncorretto-17 as builder
WORKDIR /app
COPY pom.xml .
RUN mvn verify --fail-never
COPY src/ /app/src/
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /app/target/*-SNAPSHOT.jar /app/app.jar
EXPOSE 8083
ENTRYPOINT ["java","-jar","/app/app.jar"]